In [1]:
import numpy as np 
import pandas as pd
import matplotlib as mpl

In [2]:
df=pd.read_csv("/kaggle/input/datasets/fatuzahra/irisiris/iris.csv")

In [3]:
df.head

<bound method NDFrame.head of      sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]>

In [4]:
temps=np.array([30,31,29,32,28,32,33])
print(temps.mean())
print(temps.std())

30.714285714285715
1.6659862556700857


In [5]:
numeric=df.iloc[:, 0:4].values
textual=df["species"]

In [6]:
print(numeric)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [7]:
print(textual)

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object


In [8]:
means=np.mean(numeric,axis=0)
stds=np.std(numeric,axis=0)
#axis=0 means that we want to select from row 0, or from the start
print(means)
print(stds)
#feature with the highest std value is the most imp feature of the dataset
#this feature makes it easier to make predictions
#feature with low std makes it harder to make predictions
#we can see that the petal length is the most imp feature here at it has the hightest std value

[5.84333333 3.05733333 3.758      1.19933333]
[0.82530129 0.43441097 1.75940407 0.75969263]


In [9]:
max=np.max(numeric,axis=0)
min=np.min(numeric,axis=0)
#min and max values helps find the range of a feature and also helps find outliers
#outliers are the impossible values of a feature, i.e -ve height, etc.
print(max)
print(min)

[7.9 4.4 6.9 2.5]
[4.3 2.  1.  0.1]


In [10]:
#filteringn helps us find the outliers. if there are only a few values that are close to the min or max value, then they are the outliers
sepal_long=numeric[numeric[: ,2]>4]
#in the above cell, we see that the max sepal lenght is 4.4 so we set a filter at 4 to see how many entries have sepal length close to the max value
print(sepal_long)
#since there are a lot of value, we say that it is not an outlier

[[7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [6.6 2.9 4.6 1.3]
 [5.9 3.  4.2 1.5]
 [6.1 2.9 4.7 1.4]
 [6.7 3.1 4.4 1.4]
 [5.6 3.  4.5 1.5]
 [5.8 2.7 4.1 1. ]
 [6.2 2.2 4.5 1.5]
 [5.9 3.2 4.8 1.8]
 [6.3 2.5 4.9 1.5]
 [6.1 2.8 4.7 1.2]
 [6.4 2.9 4.3 1.3]
 [6.6 3.  4.4 1.4]
 [6.8 2.8 4.8 1.4]
 [6.7 3.  5.  1.7]
 [6.  2.9 4.5 1.5]
 [6.  2.7 5.1 1.6]
 [5.4 3.  4.5 1.5]
 [6.  3.4 4.5 1.6]
 [6.7 3.1 4.7 1.5]
 [6.3 2.3 4.4 1.3]
 [5.6 3.  4.1 1.3]
 [5.5 2.6 4.4 1.2]
 [6.1 3.  4.6 1.4]
 [5.6 2.7 4.2 1.3]
 [5.7 3.  4.2 1.2]
 [5.7 2.9 4.2 1.3]
 [6.2 2.9 4.3 1.3]
 [5.7 2.8 4.1 1.3]
 [6.3 3.3 6.  2.5]
 [5.8 2.7 5.1 1.9]
 [7.1 3.  5.9 2.1]
 [6.3 2.9 5.6 1.8]
 [6.5 3.  5.8 2.2]
 [7.6 3.  6.6 2.1]
 [4.9 2.5 4.5 1.7]
 [7.3 2.9 6.3 1.8]
 [6.7 2.5 5.8 1.8]
 [7.2 3.6 6.1 2.5]
 [6.5 3.2 5.1 2. ]
 [6.4 2.7 5.3 1.9]
 [6.8 3.  5.5 2.1]
 [5.7 2.5 5.  2. ]
 [5.8 2.8 5.1 2.4]
 [6.4 3.2 5.3 2.3]
 [6.5 3.  5.5 1.8]
 [7.7 3.8 6.7 2.2]
 [7.7 2.6 6.

In [11]:
#checking for petal length
petal_long=numeric[numeric[: ,2]>6]
print(petal_long)

[[7.6 3.  6.6 2.1]
 [7.3 2.9 6.3 1.8]
 [7.2 3.6 6.1 2.5]
 [7.7 3.8 6.7 2.2]
 [7.7 2.6 6.9 2.3]
 [7.7 2.8 6.7 2. ]
 [7.4 2.8 6.1 1.9]
 [7.9 3.8 6.4 2. ]
 [7.7 3.  6.1 2.3]]


In [12]:
#now that we know that petal length is an imp feature
#and that it is not an outlier
#we will take the mean and std of each specie individually
for species in np.unique(textual):
    group=numeric[textual==species]
    print(species)
    print("Mean petal length:", group[:,2].mean())
    print("Std of petal length:", group[:,2].std())

#this helps us determine through our human intelligence that out of the three species, the one with the
#longest petal is virginica, the one with the smallest petals is setosa and versicolor lies in the middle
#this information helps us train models in identifying flowers by looking at the petal length as well

setosa
Mean petal length: 1.4620000000000002
Std of petal length: 0.17191858538273283
versicolor
Mean petal length: 4.26
Std of petal length: 0.4651881339845203
virginica
Mean petal length: 5.5520000000000005
Std of petal length: 0.546347874526844
