In [1]:
import numpy as np 
import pandas as pd
import matplotlib as mpl

In [3]:
df=pd.read_csv("/kaggle/input/datasets/fatuzahra/irisiris/iris.csv")

In [4]:
df.head

<bound method NDFrame.head of      sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]>

In [6]:
string="Hello there"
print(string[0])
print(string[-1])

H
e


In [7]:
print(string[3:10])
print(string[:2])
print(string[2:])


lo ther
He
llo there


In [8]:
upper=string.upper()
lower=string.lower()
print(upper)
print(lower)

HELLO THERE
hello there


In [10]:
words=string.split()
print(words)

['Hello', 'there']


In [11]:
joined="-".join(words)
print(joined)

Hello-there


In [17]:
replaced=joined.replace("-"," ")
print(replaced)

Hello there


In [18]:
arr=[10,3,12,23,5,0]
squares=[i ** 2 for i in arr]
print(squares)

[100, 9, 144, 529, 25, 0]


In [19]:
print(np.__version__)

2.0.2


In [48]:
#numpy is used to turn data into numerical form.

In [23]:
arr2=np.array([1,2,3,4])
#creating and array using pre-defined array() method in numpy lib
print(arr2)

[1 2 3 4]


In [25]:
shape=arr2.shape
#shape method is used to find the number of elements in a 1D array/matrix and the order of a 2D array/matrix
print(shape)

(4,)


In [27]:
print(arr2.ndim)
#ndim method is used to find the dimensions of a matrix or an array

1


In [29]:
print(arr2.dtype)
#dtype method is used to find the datatype of the elements in the array or matrix

int64


In [32]:
np.zeros(6)
#used to create an array of all zero elements. number of desired elements is passed as an arguement while calling the method

array([0., 0., 0., 0., 0., 0.])

In [33]:
np.ones(4)
#used to create an array of all ones elements

array([1., 1., 1., 1.])

In [34]:
np.arange(1,11)
#used to create an array of a range of elements. starting and ending range is passed as arguement where ending range is exclusive

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
np.arange(0,11,2)
#used to create an array with a range of elements with jumps. the last arguement specifies the jump 

array([ 0,  2,  4,  6,  8, 10])

In [40]:
matrixA=np.array([[2,4,6],[1,3,5]])
#creating a 2D array or matrix
print(matrixA)

[[2 4 6]
 [1 3 5]]


In [46]:
matrixA=np.array([[2,4,6],[1,3,5]])
print(matrixA)

matrixB=np.array([[1,2,3],[4,5,6]])
print(matrixB)
print()
print(matrixA + matrixB)
print()
print(matrixA - matrixB)

[[2 4 6]
 [1 3 5]]
[[1 2 3]
 [4 5 6]]

[[ 3  6  9]
 [ 5  8 11]]

[[ 1  2  3]
 [-3 -2 -1]]


In [49]:
score=[23,12,10,3]
print(np.mean(score))
print(np.median(score))
print(np.std(score))
print(np.min(score))
print(np.max(score))


12.0
11.0
7.176350047203662
3
23


In [ ]:
#std is the measure of how far each vlue is from the mean value
#std is used to check which data is better for computing
#it helps determine which data to eliminate and how and what data to clean
#std value also tells us how far or close the values are from each other

In [50]:
#for example, to data can have the same mean/avg value but their std value helps us determine which data is cleaner and more suitable
score1=[60,70,80]
score2=[30,70,110]
#score1 and score2 both have the same avg but their std value is very different
print("mean and std of score1:")
print(np.mean(score1))
print(np.std(score1))
print("mean and std of score2:")
print(np.mean(score2))
print(np.std(score2))

mean and std of score1:
70.0
8.16496580927726
mean and std of score2:
70.0
32.65986323710904


In [55]:
temps=np.array([30,31,29,32,28,32,33])
print(temps.mean())
print(temps.std())
#now since the std value is small, we can say that the values are close to each other
#this helps us come to the conclusion that the weather remained pretty consistent throughout the week

30.714285714285715
1.6659862556700857


In [62]:
#separating numeric and textual data from the dataset
numeric=df.iloc[:, 0:4].values
textual=df["species"]

In [64]:
print(numeric)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [63]:
print(textual)

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object
