In [1]:
import numpy as np 
import pandas as pd
import matplotlib as mpl

In [2]:
df=pd.read_csv("/kaggle/input/datasets/fatuzahra/irisiris/iris.csv")

In [3]:
df.head

<bound method NDFrame.head of      sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]>

In [4]:
string="Hello there"
print(string[0])
print(string[-1])

H
e


In [5]:
print(string[3:10])
print(string[:2])
print(string[2:])


lo ther
He
llo there


In [6]:
upper=string.upper()
lower=string.lower()
print(upper)
print(lower)

HELLO THERE
hello there


In [7]:
words=string.split()
print(words)

['Hello', 'there']


In [8]:
joined="-".join(words)
print(joined)

Hello-there


In [9]:
replaced=joined.replace("-"," ")
print(replaced)

Hello there


In [10]:
arr=[10,3,12,23,5,0]
squares=[i ** 2 for i in arr]
print(squares)

[100, 9, 144, 529, 25, 0]


In [11]:
print(np.__version__)

2.0.2


In [12]:
#numpy is used to turn data into numerical form.
#it helps determine how and what data to normalize and clean

In [13]:
arr2=np.array([1,2,3,4])
#creating and array using pre-defined array() method in numpy lib
print(arr2)

[1 2 3 4]


In [14]:
shape=arr2.shape
#shape method is used to find the number of elements in an array (or 1D matrix) and the order of a 2D matrix
print(shape)

(4,)


In [15]:
print(arr2.ndim)
#ndim method is used to find the dimensions of a matrix or an array

1


In [16]:
print(arr2.dtype)
#dtype method is used to find the datatype of the elements in the array or matrix

int64


In [17]:
np.zeros(6)
#used to create an array of all zero elements. number of desired elements is passed as an arguement while calling the method

array([0., 0., 0., 0., 0., 0.])

In [18]:
np.ones(4)
#used to create an array of all ones elements

array([1., 1., 1., 1.])

In [19]:
np.arange(1,11)
#used to create an array of a range of elements. starting and ending range is passed as arguement where ending range is exclusive

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
np.arange(0,11,2)
#used to create an array with a range of elements with jumps. the last arguement specifies the jump 

array([ 0,  2,  4,  6,  8, 10])